name: "Tools - Validate Dockerfile Schema"

on:
  pull_request:
    branches: [ "master" ]
    types: [ labeled ]
    paths:
      - '**Dockerfile'

permissions:
  contents: read
  
jobs:
  validate-dockerfile-schema:
    name: Haskell Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
          recursive: true
          ignore: "DL3008,DL3015,DL3018"
